### ISSUE TITLE
how to execute into the container

### ISSUE THREAD

**Issue by gezichenshan** [halverneus/static-file-server#53]
how to do things like _docker exec -it [container id] sh_ ?

**Comment by halverneus** [comment]
For the container that is built with the Dockerfile contained in the repository, there is no way. This is an intentional security feature. Even if there were some way to hack static-file-server, there are no tools in the container to allow an attacker to escalate or do anything (there would be no way to modify any files on the system). Additionally, by not shipping shells and other Linux tools, the image stays tiny and fast to download and deploy.

Knowing that, if you still want shell access, change the "FROM scratch" line to something like "FROM ubuntu:20.04" and build the container. You will then have access to all the tools that come with that image.

Does that answer your question?

**Comment by dsb3** [comment]
What's your purpose to exec into the container?

I'll share my example in case it's also suitable for yours.  I have a mini kube cluster; I'm using static-file-server to serve files.  I want shell access into the environment (specifically, in this case the pod, not the container) in order to manipulate the files on disk.

So - instead of a pod with one container, I have a pod with two.  The static-file-server does it's thing.  Secondly I have busybox (but I could use anything else I wanted) that shares the same volume mount, and thus can access the same files to edit them.

Here's what my Deployment looks like for that:

```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: web
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: static-web
  template:
    metadata:
      labels:
        app: static-web
    spec:
      containers:
      - image: docker.io/library/busybox:latest
        imagePullPolicy: Always
        name: busybox
        stdin: true
        tty: true
        volumeMounts:
          - mountPath: /web
            name: data
      - image: docker.io/halverneus/static-file-server:latest
        imagePullPolicy: Always
        name: web
        env:
          - name: PORT
            value: "8080"
          - name: SHOW_LISTING
            value: "true"
          - name: DEBUG
            value: "false"
          - name: FOLDER
            value: "/web/"
        volumeMounts:
          - mountPath: /web
            name: data
      securityContext:
        runAsGroup: 8080
        runAsUser: 8080
        fsGroup: 8080
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: web-content
```
