### ISSUE TITLE
unable to host as https server.

### ISSUE THREAD

**Issue by subhamsps** [halverneus/static-file-server#57]
Hi there,

I am unable to host the static file server over https and i am getting the following error :
the content of my env files are : 
cors: false
debug: true
folder: /home/user/temp
host: ""
port: 8443
show-listing: true
tls-cert: /home/user/temp/cert.pem
tls-key: /home/user/temp/mykey.pem
url-prefix: ""
referrers:
- https://localhost

sudo docker run --env-file envlist halverneus/static-file-server:latest
2021/06/07 01:25:01 Error: open /home/user/temp/cert.pem: no such file or directory

need some guidance to fix this issue.

**Comment by halverneus** [comment]
Based on what you have shared, it doesn't look like you are mounting your volumes into the container nor exposing the port to your host machine. For things to work as you have listed:

```bash
docker run --env-file envlist -p "8443:8443" -v "/home/user/temp:/home/user/temp" halverneus/static-file-server:latest
```
Having said that, I would make a couple recommendations:

- Don't put your cert.pem and mykey.pem in the same directory you are serving. That makes it easy for someone to steal your cert and pretend to be your server (low likelihood, but good security practice, nonetheless).
- You can simplify by attaching the folder to serve to /web.

Provided you want to make those changes:

```bash
docker run --env-file envlist -p "8443:8443" -v "/home/user/temp/certs:/certs" -v /home/user/temp/files:/web halverneus/static-file-server:latest
```

You will need to set:
- TLS_CERT=/certs/cert.pem
- TLS_KEY=/certs/mykey.pem
- FOLDER={Not required... just leave this entry out}

I hope that helps!

**Comment by subhamsps** [comment]
Hi Jeromy,

Thanks for your suggestions...it did help. However, on accessing the url i am getting 'Invalid Source' as an error message on the Web GUI.

![image (7)](https://user-images.githubusercontent.com/10230023/121181260-6ec8fe80-c87f-11eb-9db7-4e635d05868c.png)

have you seen this before?

**Comment by halverneus** [comment]
It appears you probably got that error because you are using referrers and the request didn't include the HTTP header "Referer". If you leave the value of Referrers blank (either don't set the environment variable or the config option), or provide an entry to the "Referer" header, the problem should go away, I suspect.

**Comment by subhamsps** [comment]
Hi Jeromy,

Thanks for your inputs..it works now 💯 
Is it possible to use docker secrets instead of using the key and cert files directly?

**Comment by subhamsps** [comment]
Hi Jeromy..
any plans to support docker secrets in future? or does it have support to use docker secrets already?

**Comment by halverneus** [comment]
My apologies for missing you last question. This does support Docker Secrets out-of-the-gate. Docker Secrets just puts files in the /run/secrets/ directory (as far as anything running inside Docker is concerned). Given that, you can add your key and cert files as secrets, then simply point to them in the configuration file or environment variables (for example "TLS_CERT=/run/secrets/my.crt").

**Comment by airbadboy-victor** [comment]
Hi Jeromy,
     We try to use "TLS_CERT=/run/secrets/my.crt" in the env-file, but it seen that it can't find the path of it with the error " Error: open /run/secrets/ssl.crt: no such file or directory".
     By the way, can I add one more question about this. Is it possible use the TLS_KEY with the -aes128 or -des3? 
      For example I used the command "openssl genrsa -aes128 -out server.key 1024" to create a key file(server.key) with the aes128 encryption.

**Comment by airbadboy-victor** [comment]
Hi Jeromy,
We try to use "TLS_CERT=/run/secrets/ssl.crt" in the env-file, but it seen that it can't find the path of it with the error " Error: open /run/secrets/ssl.crt: no such file or directory".
By the way, can I add one more question about this. Is it possible use the TLS_KEY with the -aes128 or -des3?
For example I used the command "openssl genrsa -aes128 -out server.key 1024" to create a key file(server.key) with the aes128 encryption.

**Comment by halverneus** [comment]
I would be interested in your full key and certificate generation steps. With the steps that follow, I tried building off of the command you provided to make the server.key and server.crt files:

```bash
openssl genrsa -aes128 -out server.key 1024
openssl req -new -x509 -key server.key -out server.crt
```

And the end result was:

```
Error: tls: failed to parse private key
```

Having said that, here are the steps I just quickly tested that work:

```bash
openssl req -newkey rsa:2048 -nodes -keyout server.key -x509 -days 365 -out server.crt
docker swarm init
docker secret create key server.key
docker secret create crt server.crt
docker stack up -c docker-compose.yml sfs
```

... and the contents of docker-compose.yml:

```yaml
version: "3.7"

secrets:
  key:
    external: true
  crt:
    external: true

services:
  sfs:
    image: halverneus/static-file-server:v1.8.3
    secrets:
      - source: key
        target: server.key
      - source: crt
        target: server.crt
    ports:
      - "443:8080"
    volumes:
      - "/home/jstreets/tmp/secrets:/web"
    environment:
      - TLS_CERT=/run/secrets/server.crt
      - TLS_KEY=/run/secrets/server.key
```

This worked without any issues. I don't see the "no such file or directory" issue you were having, but you might (or might not) have an issue with your certificate/key once you get past the missing file issue. I hope this is enough to get you on the right path.

**Comment by airbadboy-victor** [comment]
Hi Jeromy,
Thanks for the answer. It is very helpful. 
I have try the solution that you offer. And do all step as below:
generate a ssl key and certificate
```
openssl genrsa -out ssl.key 2048 
openssl req -new -key ssl.key -out ssl.csr
openssl x509 -req -days 365 -in ssl.csr -signkey ssl.key -out ssl.crt
```
create docker secret
```
docker secret create file_server_KEY_FILE ssl.key
docker secret create file_server_CERT_FILE ssl.crt
```
edit the yml file(static-file-server.yml)
```
version: "3.7"

secrets:
  file_server_KEY_FILE:
    external: true
  file_server_CERT_FILE:
    external: true

services:
  sfs:
    image: halverneus/static-file-server:latest
    secrets:
      - source: file_server_KEY_FILE
        target: ssl.key
      - source: file_server_CERT_FILE
        target: ssl.crt
    ports:
      - "8448:8448"
    volumes:
      - "/home/siguser/https-server:/web"
    environment:
      - TLS_CERT=/run/secrets/ssl.crt
      - TLS_KEY=/run/secrets/ssl.key
```
use docker swarm to start the service
`docker stack up -c static-file-server.yml sfs `
use docker stack ls check about it ,and find out the service is working well
```
NAME                SERVICES            ORCHESTRATOR
sfs                 1                   Swarm
```
use docker service ls check about the service status
`s6revhqqsdqc        sfs_sfs              replicated          1/1                 halverneus/static-file-server:latest                  *:8448->8448/tcp`
It seem that the service is working good. But I find it not work when I check it with browser
![image](https://user-images.githubusercontent.com/68526716/122175186-04831000-ceb6-11eb-9b9d-6e62230cc7ff.png)
Do you know what is the problem is?

**Comment by airbadboy-victor** [comment]
We have try docker service to start the service
`docker service create --name https-server --secret file_server_CERT_FILE --secret file_server_KEY_FILE --env-file envlist -p "8448:8448" --mount type=bind,source=/home/siguser/https-server,target=/web halverneus/static-file-server:latest`
the env-file(envlist ) content as below:
```
DEBUG=true
PORT=8448
SHOW_LISTING=true
TLS_CERT=/run/secrets/file_server_CERT_FILE
TLS_KEY=/run//secrets/file_server_KEY_FILE
```
And it is working fine:
```
9zk8s2u3ewlwqb78g7z3azqnp
overall progress: 1 out of 1 tasks
1/1: running   [==================================================>]
verify: Service converged
```
 I check in the browser , it working fine too:
![image](https://user-images.githubusercontent.com/68526716/122176921-b2db8500-ceb7-11eb-9c6a-d2c341fe7c4a.png)
But we think your solution using docker swarm is a better solution then ours. We would appreciate it if you could give us some advice on how to solve the problem when we use the docker swarm to start the service.

**Comment by halverneus** [comment]
I think the problem is your PORT assignment. By default, SFS uses port 8080. In your compose file, I didn't see the environment variable for PORT=8448 being assigned. That would explain why you wouldn't be able to see it at your endpoint. You can either as PORT as an environment variable...

```yaml
...
environment:
  - PORT=8448
...
```

**Comment by airbadboy-victor** [comment]
Hi Hi Jeromy,
Thanks for the replying. I try add the port as you said. But it still not work. Do I miss something.  As below is the yml file I am using.
```
version: "3.7"

secrets:
  file_server_KEY_FILE:
    external: true
  file_server_CERT_FILE:
    external: true

services:
  sfs:
    image: halverneus/static-file-server:latest
    secrets:
      - source: file_server_KEY_FILE
        target: ssl_pri.key
      - source: file_server_CERT_FILE
        target: ssl.crt
    ports:
      - "8448"
    volumes:
      - "/home/siguser/https-server:/web"
    environment:
      - PORT=8448
      - TLS_CERT=/run/secrets/file_server_CERT_FILE
      - TLS_KEY=/run/secrets/file_server_KEY_FILE

```
